// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Code      string
	Name      string
	Type      string
	ParentID  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Category struct {
	ID          uuid.UUID
	Name        string
	Type        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     sql.NullString
	Phone     sql.NullString
	Address   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID              uuid.UUID
	TransactionDate time.Time
	ReferenceNumber sql.NullString
	Description     sql.NullString
	TransactionType string
	CustomerID      sql.NullString
	TotalAmount     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TransactionItem struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	CategoryID    sql.NullString
	Debit         string
	Credit        string
	Description   sql.NullString
	CreatedAt     time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Email        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

