// Code generated by sqlc. DO NOT EDIT.
// This is a placeholder - will be generated by sqlc

package db

import (
	"context"

	"github.com/google/uuid"
)

type Queries struct {
	db DBTX
}

type DBTX interface {
	QueryRow(context.Context, string, ...interface{}) Row
	Query(context.Context, string, ...interface{}) (Rows, error)
	Exec(context.Context, string, ...interface{}) (Result, error)
}

type Row interface {
	Scan(dest ...interface{}) error
}

type Rows interface {
	Close()
	Next() bool
	Err() error
	Scan(dest ...interface{}) error
}

type Result interface {
	LastInsertId() (int64, error)
	RowsAffected() (int64, error)
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	// Placeholder - will be generated by sqlc
	return User{}, nil
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	// Placeholder - will be generated by sqlc
	return User{}, nil
}

